version: "3.9"

services:
  calculator-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calculator-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
